### ISSUE TITLE
Add ability to rotate matrix vertically

### ISSUE THREAD

**Issue by mnmartinelli** [wymcg/matricks#91]
Add option to flip the entire matrix display vertically (i.e. with a --vertical/--landscape option)

**Comment by wymcg** [comment]
Good idea, thanks @mnmartinelli! `--vertical` is already used by the vertically wired matrix option added in #86, but a similar feature is proposed to flip the matrix horizontally in #87 with a `--mirror` flag. What if we did something like `--mirror-vertical` and `--mirror-horizontal` for vertical and horizontal flips?
